### ISSUE TITLE
added news not appearing

### ISSUE THREAD

**Issue by bergel** [bergel/ISCL#2]
I created a file `_news/2018-10-14-BestPaperAtESUG.md`, but it does not appear in the news when I open the website.

**Comment by tinchodias** [comment]
I couldn't reproduce. I did `git pull` and then `bundle exec jekyll serve --livereload` the the news were there when I opened the localhost:4000 at browser.

Did you add --incremental option? I experienced the effect you described when I used this option in the past.

**Comment by bergel** [comment]
It works now... 
I close this issue.
